"""
Data models for Supply Chain Visibility application.

This module defines the core data structures used throughout the application,
including shipments, inventory items, suppliers, network nodes, alerts, and status updates.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, List, Optional


# Enumerations

class ShipmentStatus(Enum):
    """Status of a shipment in the supply chain."""
    PENDING = "pending"
    IN_TRANSIT = "in_transit"
    DELAYED = "delayed"
    DELIVERED = "delivered"


class NodeType(Enum):
    """Type of node in the supply chain network."""
    SUPPLIER = "supplier"
    WAREHOUSE = "warehouse"
    DESTINATION = "destination"


class NodeStatus(Enum):
    """Operational status of a network node."""
    NORMAL = "normal"
    CONGESTED = "congested"
    DISRUPTED = "disrupted"


class AlertType(Enum):
    """Type of alert generated by the system."""
    SHIPMENT_DELAY = "shipment_delay"
    LOW_STOCK = "low_stock"
    SUPPLIER_PERFORMANCE = "supplier_performance"


class AlertSeverity(Enum):
    """Severity level of an alert."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# Data Models

@dataclass
class Shipment:
    """
    Represents a shipment in the supply chain.
    
    Attributes:
        id: Unique identifier for the shipment
        origin: Starting location of the shipment
        destination: Target delivery location
        current_location: Current position in transit
        status: Current shipment status
        estimated_delivery: Expected delivery timestamp
        actual_delivery: Actual delivery timestamp (None if not delivered)
        items: List of item identifiers in the shipment
        supplier_id: Identifier of the supplier providing the shipment
        created_at: Timestamp when shipment was created
        updated_at: Timestamp of last update
    """
    id: str
    origin: str
    destination: str
    current_location: str
    status: ShipmentStatus
    estimated_delivery: datetime
    actual_delivery: Optional[datetime]
    items: List[str]
    supplier_id: str
    created_at: datetime
    updated_at: datetime
    
    def __post_init__(self):
        """Validate shipment data after initialization."""
        if not self.id:
            raise ValueError("Shipment id cannot be empty")
        if not self.origin:
            raise ValueError("Shipment origin cannot be empty")
        if not self.destination:
            raise ValueError("Shipment destination cannot be empty")
        if not self.supplier_id:
            raise ValueError("Shipment supplier_id cannot be empty")


@dataclass
class InventoryItem:
    """
    Represents an inventory item tracked in the supply chain.
    
    Attributes:
        id: Unique identifier for the inventory item
        name: Name of the item
        category: Category classification
        location: Current storage location
        quantity: Current quantity in stock
        unit: Unit of measurement (e.g., "pieces", "kg")
        reorder_point: Threshold quantity for reordering
        last_updated: Timestamp of last inventory update
    """
    id: str
    name: str
    category: str
    location: str
    quantity: float
    unit: str
    reorder_point: float
    last_updated: datetime
    
    def __post_init__(self):
        """Validate inventory item data after initialization."""
        if not self.id:
            raise ValueError("InventoryItem id cannot be empty")
        if not self.name:
            raise ValueError("InventoryItem name cannot be empty")
        if self.quantity < 0:
            raise ValueError("InventoryItem quantity cannot be negative")
        if self.reorder_point < 0:
            raise ValueError("InventoryItem reorder_point cannot be negative")


@dataclass
class Supplier:
    """
    Represents a supplier in the supply chain.
    
    Attributes:
        id: Unique identifier for the supplier
        name: Supplier name
        contact: Contact information
        performance_score: Overall performance score (0-100)
        on_time_delivery_rate: Percentage of on-time deliveries (0-100)
        quality_score: Quality rating (0-100)
        average_lead_time: Average lead time in days
        total_shipments: Total number of shipments handled
        last_updated: Timestamp of last update
    """
    id: str
    name: str
    contact: str
    performance_score: float
    on_time_delivery_rate: float
    quality_score: float
    average_lead_time: float
    total_shipments: int
    last_updated: datetime
    
    def __post_init__(self):
        """Validate supplier data after initialization."""
        if not self.id:
            raise ValueError("Supplier id cannot be empty")
        if not self.name:
            raise ValueError("Supplier name cannot be empty")
        if not 0 <= self.performance_score <= 100:
            raise ValueError("Supplier performance_score must be between 0 and 100")
        if not 0 <= self.on_time_delivery_rate <= 100:
            raise ValueError("Supplier on_time_delivery_rate must be between 0 and 100")
        if not 0 <= self.quality_score <= 100:
            raise ValueError("Supplier quality_score must be between 0 and 100")
        if self.average_lead_time < 0:
            raise ValueError("Supplier average_lead_time cannot be negative")
        if self.total_shipments < 0:
            raise ValueError("Supplier total_shipments cannot be negative")


@dataclass
class Node:
    """
    Represents a node in the supply chain network.
    
    Attributes:
        id: Unique identifier for the node
        name: Node name
        type: Type of node (supplier, warehouse, destination)
        location: Location description
        latitude: Geographic latitude (optional)
        longitude: Geographic longitude (optional)
        status: Operational status of the node
        capacity: Maximum capacity (optional)
    """
    id: str
    name: str
    type: NodeType
    location: str
    latitude: Optional[float]
    longitude: Optional[float]
    status: NodeStatus
    capacity: Optional[float]
    
    def __post_init__(self):
        """Validate node data after initialization."""
        if not self.id:
            raise ValueError("Node id cannot be empty")
        if not self.name:
            raise ValueError("Node name cannot be empty")
        if self.latitude is not None and not -90 <= self.latitude <= 90:
            raise ValueError("Node latitude must be between -90 and 90")
        if self.longitude is not None and not -180 <= self.longitude <= 180:
            raise ValueError("Node longitude must be between -180 and 180")
        if self.capacity is not None and self.capacity < 0:
            raise ValueError("Node capacity cannot be negative")


@dataclass
class Edge:
    """
    Represents a connection between nodes in the supply chain network.
    
    Attributes:
        id: Unique identifier for the edge
        source_node_id: ID of the source node
        target_node_id: ID of the target node
        shipment_ids: List of shipment IDs using this route
        active: Whether the edge is currently active
    """
    id: str
    source_node_id: str
    target_node_id: str
    shipment_ids: List[str]
    active: bool
    
    def __post_init__(self):
        """Validate edge data after initialization."""
        if not self.id:
            raise ValueError("Edge id cannot be empty")
        if not self.source_node_id:
            raise ValueError("Edge source_node_id cannot be empty")
        if not self.target_node_id:
            raise ValueError("Edge target_node_id cannot be empty")
        if self.source_node_id == self.target_node_id:
            raise ValueError("Edge source and target nodes cannot be the same")


@dataclass
class Alert:
    """
    Represents an alert generated by the system.
    
    Attributes:
        id: Unique identifier for the alert
        type: Type of alert
        severity: Severity level
        message: Alert message text
        entity_id: ID of the related entity (shipment, item, or supplier)
        created_at: Timestamp when alert was created
        acknowledged: Whether the alert has been acknowledged
        acknowledged_at: Timestamp when alert was acknowledged (None if not acknowledged)
    """
    id: str
    type: AlertType
    severity: AlertSeverity
    message: str
    entity_id: str
    created_at: datetime
    acknowledged: bool
    acknowledged_at: Optional[datetime]
    
    def __post_init__(self):
        """Validate alert data after initialization."""
        if not self.id:
            raise ValueError("Alert id cannot be empty")
        if not self.message:
            raise ValueError("Alert message cannot be empty")
        if not self.entity_id:
            raise ValueError("Alert entity_id cannot be empty")
        if self.acknowledged and self.acknowledged_at is None:
            raise ValueError("Alert acknowledged_at must be set when acknowledged is True")


@dataclass
class StatusUpdate:
    """
    Represents a status update for an entity in the system.
    
    Attributes:
        entity_type: Type of entity being updated ("shipment", "inventory", "supplier")
        entity_id: ID of the entity being updated
        field: Name of the field being updated
        old_value: Previous value of the field
        new_value: New value of the field
        timestamp: Timestamp of the update
    """
    entity_type: str
    entity_id: str
    field: str
    old_value: Any
    new_value: Any
    timestamp: datetime
    
    def __post_init__(self):
        """Validate status update data after initialization."""
        if not self.entity_type:
            raise ValueError("StatusUpdate entity_type cannot be empty")
        if self.entity_type not in ["shipment", "inventory", "supplier"]:
            raise ValueError("StatusUpdate entity_type must be 'shipment', 'inventory', or 'supplier'")
        if not self.entity_id:
            raise ValueError("StatusUpdate entity_id cannot be empty")
        if not self.field:
            raise ValueError("StatusUpdate field cannot be empty")


@dataclass
class SupplyChainData:
    """
    Container for all supply chain data.
    
    Attributes:
        shipments: List of all shipments
        inventory: List of all inventory items
        suppliers: List of all suppliers
        nodes: List of all network nodes
        edges: List of all network edges
        last_updated: Timestamp of last data update
    """
    shipments: List[Shipment]
    inventory: List[InventoryItem]
    suppliers: List[Supplier]
    nodes: List[Node]
    edges: List[Edge]
    last_updated: datetime
